---
name: learn-bosh
director_uuid: 28539132-6d43-4e1b-bf40-f2ce032ee9f8

releases:
- name: learn-bosh
  version: latest

networks:
- name: default
  subnets:
  - range: 10.244.50.0/28
    reserved: [10.244.50.1]
    static: [10.244.50.2,10.244.50.6,10.244.50.10]
    cloud_properties:
      name: random

resource_pools:
- name: default
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  network: default
  cloud_properties: {}

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

jobs:
- name: app
  templates:
  - name: app
  instances: 2
  resource_pool: default
  networks:
  - name: default
    static_ips:
    - 10.244.50.2
    - 10.244.50.6
  properties:
    port: 8888
- name: router
  templates:
  - name: router
  instances: 1
  resource_pool: default
  networks:
  - name: default
    static_ips: [10.244.50.10]
  properties:
    servers: ['http://10.244.50.2:8888','http://10.244.50.6:8888']
